### ISSUE TITLE
SEB Version 2.4 not starting for installation?

### ISSUE THREAD

**Issue by Itshayat** [SafeExamBrowser/seb-testing#6]
Hi SEB Team,
I have an issue on my SEB when I click begin for SEB installation so it not starting I don't know please help me what that issue?

**Comment by danschlet** [comment]
Hi
There is no SEB version 4. Please provide all the necessary information (listed [here](https://safeexambrowser.org/support_en.html)), otherwise we cannot help.

**Comment by marketerhayatofficial** [comment]
im sorry im talking about version 2.4 
when i click on it for installation so it's didn't take start? can you tell what is that issue?
